export const WAREHOUSE_LOADING = 'WAREHOUSE_LOADING';
export const ADD_WAREHOUSE = 'ADD_WAREHOUSE';
export const WAREHOUSE_FAILED = 'WAREHOUSE_FAILED';
export const EDIT_WAREHOUSE = 'EDIT_WAREHOUSE';
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE';

